image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: maven:3.8.6-jdk-11-slim
  only:
    - dev
  script:
    - echo "Compiling..."
    - mvn compile -Dmaven.repo.local=./.m2/repository
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  image: maven:3.8.6-jdk-11-slim
  only:
    - dev
  script:
    - echo "Testing the code..."
    - mvn test -Dmaven.repo.local=./.m2/repository
  cache:
    paths:
      - ./target
      - ./.m2

package:
  stage: package
  image: maven:3.8.6-jdk-11-slim
  only:
    - dev
  script:
    - echo "Packging..."
    - mvn package -am -o -Dmaven.test.skip -T 1C -Dmaven.repo.local=./.m2/repository
  artifacts:
    paths:
      - target/backend.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

deploy:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deploying..."
    - echo "Application successfully deployed."
