stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  only:
    - dev
  tags:
    - socialnet_runner
  script:
    - echo "Compiling..."
    - mvn compile -Dmaven.repo.local=./.m2/repository
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  only:
    - dev
  tags:
    - socialnet_runner
  script:
    - echo "Testing..."
    - mvn test -Dmaven.repo.local=./.m2/repository
  cache:
    paths:
      - ./target
      - ./.m2

package:
  stage: package
  only:
    - dev
  tags:
    - socialnet_runner
  script:
    - echo "Packging..."
    - mvn package -am -Dmaven.test.skip -T 1C -Dmaven.repo.local=./.m2/repository
  artifacts:
    paths:
      - target/javapro37backend-0.0.1-SNAPSHOT.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

deploy:
  stage: deploy
  only:
    - dev
  tags:
    - socialnet_runner
  script:
    - echo "Deploying..."
    - docker ps --filter="name=backend" -q | xargs docker stop | xargs docker rm
    - docker images -f "dangling=true" -q | xargs docker rmi
    - docker images --filter="reference=backend" -q | xargs docker rmi
    - docker volume ls -q | xargs docker volume rm
    - docker build -t backend .
    - docker run --name="backend" -d -p 8086:8086 backend
    #- docker-compose down
    #- docker-compose up --build -d
