server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: alexsandr
    password: Fghtkm11
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: classpath:db.changelog/db.changelog-master.xml