spring:
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedInserts: true
    platform: postgres
    url: jdbc:postgresql://localhost:5432/socialnet
    username: postgres
    password: test

  security:
    user:
      name: admin
      password: admin
