spring:
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedInserts: true
    platform: postgres
    url: jdbc:postgresql://localhost:5432/socialnet
    username: postgres
    password: test

  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.mail.ru
    port: 2525
    username: java.development@mail.ru
    password: eDhZJ9bk8t0hx2WNDAev
    protocol: smtp

mail:
  transport:
    protocol: smtp
  debug: true
  smtp:
    auth: true
    starttls: true
    ssl:
      enable: true

