server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8086
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 198855
    url: jdbc:postgresql://localhost:5432/db
    initialization-mode: never
  security:
    user:
      name: admin
      password: admin
auth:
  secret: socialNet
