
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: 85778577
    url: jdbc:postgresql://localhost:5432/test

schedules:
  deleteOldCaptchasInterval: 0 0 0 * * *
  deletePostsInterval: 0 0 1 * * *
  deleteLikesInterval: 0 0 1 * * *
  birthDatePush: 0 1 8 * * *

  #--------------------------------------------------------
s3:
  accessKey: YCAJE83YiyNT766OLADHNeObE
  secretKey: YCMxows8B0JbmMtTWNcbdv3EtYq0TAO0i2minApz
  bucket: socnet37
weather:
  apiKey: 3d29686077f7a60e5b5714b659a688dd

mail:
  transport:
    protocol: smtp
  debug: true
  smtp:
    auth: true
    starttls: true
    ssl:
      enable: true

mailFrom: java.development@mail.ru
defaultPhoto: https://storage.yandexcloud.net/socnet37/users_photo/man.png
baseUrl: http://localhost:8080/
  #--------------------------------------------------------