server:
  port: ${PORT:8086}
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: mets
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedInserts: true
    platform: postgres
    url: jdbc:postgresql://localhost:5432/socialnet
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
  security:
    user:
      name: admin
      password: admin
auth:
  secret: socialNet
  timeLive: 216000
  logging:
    yandexToken: "OAuth y0_AgAAAABpyRv7AADLWwAAAADgTODc9qxs-Et7T1GdZE2muWAFM0eiubA"
s3:
  accessKey: YCAJE83YiyNT766OLADHNeObE
  secretKey: YCMxows8B0JbmMtTWNcbdv3EtYq0TAO0i2minApz
  bucket: socnet37
weather:
  apiKey: 3d29686077f7a60e5b5714b659a688dd

schedules:
  deleteOldCaptchasInterval: 0 0 0 * * *
  deletePostsInterval: 0 0 1 * * *
  deleteLikesInterval: 0 0 1 * * *
